app: springboot
port: 8080
namespace: default
replicaCount: 1
repository:
 name: springboot
 image: <id>.dkr.ecr.ap-southeast-2.amazonaws.com
 tag: latest
 pullPolicy: Always


service:
 name: springboot-service
 type: ClusterIP


hpa:
 minReplicas: 1
 maxReplicas: 5
 targetMemoryUtilizationPercentage: 180  //rough estimated calculation